### ISSUE TITLE
Empty fields at end of row are omitted

### ISSUE THREAD

**Issue by SydMontague** [AriaFallah/csv-parser#10]
Using this example CSV:

F1| F2 | F3 | F4 | F5 | F6 | F7
--- | --- | --- | --- | --- | --- | ---
a | b | c | d | e | f | 
A | B | C | D | E | F | G

```
F1,F2,F3,F4,F5,F6,F7
a,b,c,d,e,f,
A,B,C,D,E,F,G
```

Each row is supposed to contain 7 columns. However, the parser will only return 6 columns for the first data row. This seems to be caused by the fact that the last field is empty, i.e. the comma is directly followed by a CR LF.

This should not happen since according to [RFC4180](https://tools.ietf.org/html/rfc4180) `The last field in the record must not be followed by a comma`. Therefore the last, empty, field should be recognized as such instead of being skipped.

It only happens with unquoted CSV. `a,b,c,d,e,f,""` would parse properly for example. 

___

I was able to fix this issue locally by adjusting the finite state machine
```cpp

case State::START_OF_FIELD:
	m_cursor++;
	if (c == m_terminator) {
		handle_crlf(c);
		return Field(FieldType::ROW_END);
	}
```
to
```cpp

case State::START_OF_FIELD:
	m_cursor++;
	if (c == m_terminator) {
		handle_crlf(c);
		m_state = State::END_OF_ROW;
		return Field(m_fieldbuf);
	}
```

From what I understand this should only handle the special case of a CR LF directly after a separator char, i.e. the case that seems to be handled improperly.

**Comment by AriaFallah** [comment]
Thanks for the detailed bug report! This makes a lot of sense to fix. Since you already have the code figured out, would it be ridiculous of me to ask for you to open a PR up for this?

**Comment by SydMontague** [comment]
Sure thing. :)
