### ISSUE TITLE
Crash in assignment of `std::unique_ptr<char[]>`

### ISSUE THREAD

**Issue by emmenlau** [AriaFallah/csv-parser#15]
Hi, thanks for the nice work. I'm using the csv-parser since I while and it works well. However with the latest update there is a crash with clang-11 on Ubuntu 20.04. I could trace it in debugger to the following line:

https://github.com/AriaFallah/csv-parser/blob/544c764d0585c61d4c3bd3a023a825f3d7de1f31/parser.hpp#L66

The code crashes with SIGSEGV. I could not immediately see whats wrong.

**Comment by SydMontague** [comment]
What code do you use to trigger this crash?

I wasn't able to reproduce the crash using clang-11 on Linux Mint 20.1 (based on Ubuntu 20.04), using the tests and benchmarks...

**Comment by emmenlau** [comment]
I'm not 100% certain that the crash is not unrelated and caused by memory corruption in another part of the application. I'll close this issue and re-open after further investigation...
