### ISSUE TITLE
Can we access fields based on the field name?

### ISSUE THREAD

**Issue by ajtruckle** [AriaFallah/csv-parser#16]
The first row in my CSV has the headings. Can we access the values based on the headings?

**Comment by AriaFallah** [comment]
No sorry. I intentionally kept the scope of this parser really small so it can stay simple. https://github.com/vincentlaucsb/csv-parser#indexing-by-column-names is a good alternative if you want that feature. If you can't use that library for whatever reason, it shouldn't be too hard to build that feature on top of this library yourself.

**Comment by ajtruckle** [comment]
Alright. Thanks for your response.
