### ISSUE TITLE
What license is the code under?

### ISSUE THREAD

**Issue by jpoprof** [AriaFallah/csv-parser#2]
Hello Aria,
you have produced nice code. 
What is the license of your code?
Public Domain, GPL, BSD, LGPL, MIT, ...?

I couldn't get any information on it.

Thanks

**Comment by AriaFallah** [comment]
It's now under the MIT license. Thanks for reminding me to do that.

https://github.com/AriaFallah/csv-parser/commit/f5bbefa708ae563fc5013bdfec66697564efcf67
