### ISSUE TITLE
'./catch.hpp' file not found

### ISSUE THREAD

**Issue by ahmad88me** [AriaFallah/csv-parser#6]
parser_test.cpp:4:10: fatal error: './catch.hpp' file not found
#include "./catch.hpp"
         ^~~~~~~~~~~~~
1 error generated.

**Comment by AriaFallah** [comment]
Yeah not sure why I put it in the .gitignore when I made this repo...will fix

**Comment by AriaFallah** [comment]
https://github.com/AriaFallah/csv-parser/commit/e3c1207f4de50603a4946dc5daa0633ce31a9257
