### ISSUE TITLE
Utf8 BOM is not skipped

### ISSUE THREAD

**Issue by OneManMonkeySquad** [AriaFallah/csv-parser#7]
See title.

**Comment by AriaFallah** [comment]
Lol after taking years to think about this, I'm just going to say this is out of scope for this project.

**Comment by ajtruckle** [comment]
Oh dear - just found this.

**Comment by ajtruckle** [comment]
Sorry this is 5 years late! But see:

https://github.com/AriaFallah/csv-parser/issues/22
